### ISSUE TITLE
Boost -> Catch Exercise Conversions

### ISSUE THREAD

**Issue by patricksjackson** [exercism/cpp#253]
Setting this up to track the total list of exercises that need to be converted. This is part of #233.

Here's the full list of exercises, not including the 2 open problems in PRs. I plan to work mostly top down according to this list, as this reflects the order that students will encounter the problems.

When I setup PRs I will be doing it in groups where it makes sense, probably with how they're grouped below. If nobody LGTMs, I'll leave the PRs up for at least a week and then push them myself unless I think there's something that needs more consensus. If I do get some LGTMs, I may push them faster.

I'm merging these in with 1 commit per problem, and doing a rebase and merge so that every commit is present in the master branch.

Unlocked by nothing:
- [x] acronym #254
- [x] all-your-base #254
- [x] binary #254
- [x] hexadecimal #254
- [x] isogram #254
- [x] luhn #249
- [x] pascals-triangle #254
- [x] robot-simulator #254
- [x] scrabble-score #254

Core exercises and their child dependencies:
- [x] hello-world #244
    - [x] grade-school #255
    - [x] hamming #255
    - [x] nucleotide-count #255
    - [x] rna-transcription #255
- [x] leap #244
    - [x] difference-of-squares #256
    - [x] nth-prime #256
    - [x] queen-attack #256
    - [x] say #256
    - [x] sieve #256
- [x] reverse-string #244
    - [x] allergies #257
    - [x] gigasecond #261
    - [x] prime-factors #257
    - [x] robot-name #257
    - [x] sum-of-multiples #257
- [x] space-age #244
    - [x] beer-song #258
    - [x] clock #258
    - [x] meetup #261
- [x] triangle #244
    - [x] atbash-cipher #258
    - [x] binary-search #258
    - [x] trinary #258
- [x] grains #244
    - [x] food-chain #259
    - [x] phone-number #259
    - [x] roman-numerals #259
    - [x] series #259
- [x] raindrops #244
    - [x] bob #260
    - [x] crypto-square #260
    - [x] word-count #260
- [x] pangram #244
    - [x] anagram #260
    - [x] binary-search-tree #248
    - [x] bracket-push #260
    - [x] etl #260

**Comment by patricksjackson** [comment]
Every exercise now has an open PR, and each PR has a planned merge date in the description for either April 13th or April 20th, the next 2 Saturdays.

If you'd like to help, read over the changes made to the test suites and give a :+1: on the PRs if you don't see anything obviously wrong, or call out issues if you do. The only real way I could've messed up and not found it in testing is if I somehow deleted full tests or changed the test cases. I read all the changelists looking for that so I consider it fairly unlikely to have happened.

Gigasecond/Meetup will still have a dependency on Boost::date_time as discussed in #224, but everything else has 0 references to Boost.

**Comment by KevinWMatthews** [comment]
Awesome! Quick work.

**Comment by HenryRLee** [comment]
I have a question. Is it possible that we modify the download script to use a single `catch.hpp` file, instead of copying it in every exercise?

**Comment by patricksjackson** [comment]
@HenryRLee The exercism/cli team would need to support that, and they haven't been interested. The C track has the same issue.

It's not actually as simple as it sounds either, since they'd need to make sure the right version is downloaded, and we'd need to maintain backwards compat forever. The problem is that students get pinned to a git commit when they first checkout an exercise, and only ever get updated to the latest test versions if they request it manually.

**Comment by HenryRLee** [comment]
@patricksjackson Cool! It's been a great progress anyway.

**Comment by patricksjackson** [comment]
All done and merged, closing.
