### ISSUE TITLE
[v3] Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/cpp#427]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/cpp/issues/418)
- [ ] [Add key features](https://github.com/exercism/cpp/issues/419)
- [ ] [Add tags](https://github.com/exercism/cpp/issues/420)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/cpp/issues/421)
- [ ] [Update status of track](https://github.com/exercism/cpp/issues/425)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/cpp/issues/426)
- [ ] [Pass linting checks](https://github.com/exercism/cpp/issues/422)
- [ ] [Build Test Runner](https://github.com/exercism/cpp/issues/423)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/cpp/issues/424) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
