### ISSUE TITLE
Update test cases

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#775]
Grab what you want, mark it and make a PR. These exercises need updates:

- [ ] allergies
- [ ] anagram
- [ ] armstrong-numbers
- [ ] bank-account
- [ ] complex-numbers
- [ ] crypto-square
- [ ] gigasecond
- [ ] grade-school
- [ ] hamming
- [ ] high-scores
- [ ] isogram
- [ ] luhn
- [ ] matching-brackets
- [ ] pangram
- [ ] perfect-numbers
- [ ] phone-number
- [ ] prime-factors
- [ ] protein-translation
- [ ] say
- [ ] triangle
- [ ] word-count

**Comment by vaeng** [comment]
I will start with: allergies

**Comment by CadeMichael** [comment]
I'd love to help but am not sure what needs updating?

**Comment by IsaacG** [comment]
> I'd love to help but am not sure what needs updating?

The above exercises need their tests synced from the problem specs.

See docs for 
* [Practice Exercises](https://exercism.org/docs/building/tracks/practice-exercises)
* [configlet tool: syncing](https://exercism.org/docs/building/configlet#h-syncing-exercise-data-with-the-problem-specifications-repo)

Reading through prior commits on this repo (look for PRs that mention syncing tests) might prove helpful.

**Comment by vaeng** [comment]
@CadeMichael 
Give me some time, I'll write a how-to for Test Cases and put it in the tracks wiki.

**Comment by vaeng** [comment]
Here is a [wiki entry on test case updates](https://github.com/exercism/cpp/wiki/Test-Cases-for-Practice-Exercises) to explain what I have been doing so far, maybe it is helpful for you  @CadeMichael 
Do you have additions or suggestions @siebenschlaefer ?

**Comment by CadeMichael** [comment]
Thank You I'll check it out and try to update for anagram!

**Comment by CadeMichael** [comment]
Sorry for the slow progress long weekend. I got configlet working and found the testcases that need improvement

```
[warn] anagram: missing 6 test cases
       - detects two anagrams (03eb9bbe-8906-4ea0-84fa-ffe711b52c8b)
       - does not detect an anagram if the original word is repeated (630abb71-a94e-4715-8395-179ec1df9f91)
       - words are not anagrams of themselves (68934ed0-010b-4ef9-857a-20c9012d1ebf)
       - words are not anagrams of themselves even if letter case is partially different (589384f3-4c8a-4e7d-9edc-51c3e5f0c90e)
       - words are not anagrams of themselves even if letter case is completely different (ba53e423-7e02-41ee-9ae2-71f91e6d18e6)
       - words other than themselves can be anagrams (33d3f67e-fbb9-49d3-a90e-0beb00861da7)
``` 

will get a pr done tomorrow

**Comment by IsaacG** [comment]
Make sure you pull the data from the problem specs!

**Comment by CadeMichael** [comment]
> Make sure you pull the data from the problem specs!

I think that configlet does this automatically ? from my understanding but I'm not sure.

**Comment by CadeMichael** [comment]
I think I got it. I found the missing tests id's correspond to the same named tests (as already implemented) with different inputs so I've added the testcases and updated the test.toml. I'm not sure if I should be manually updating the toml with the id's of the testcases added but I don't see an automated way of doing it.

**Comment by IsaacG** [comment]
I *think* the `configlet sync` command can update that file.

**Comment by CadeMichael** [comment]
#784 

submitted a PR, sorry for all the questions, I think I got the hang of it and made the updates.

**Comment by DebbieSan** [comment]
Hi everyone! I will start working on **triangle.** First time here so checking out the documentation and will try to update.

**Comment by DebbieSan** [comment]
I submitted a PR for revision [https://github.com/exercism/cpp/pull/787](787).

Please advise, thank you!

**Comment by ahans** [comment]
Here is a PR that updates `hamming`: #789 I don't think it's worth discussing this on the forum.

**Comment by ahans** [comment]
Here is an update for `armstrong-numbers`: #808

**Comment by ahans** [comment]
And here goes a sync of `gigasecond`: #809

**Comment by KevDi** [comment]
i will take the bank-account

**Comment by KevDi** [comment]
I will also update the complex-numbers

**Comment by BNAndras** [comment]
I can take care of pangram and isogram.

**Comment by ahans** [comment]
I'm taking crypto-square.

**Comment by BNAndras** [comment]
I'll grab protein translation for next week.

**Comment by tanno1** [comment]
First time here. I'll take phone-numbers to start.

**Comment by vaeng** [comment]
@tanno1 
You are right. I checked the problem spec and there should be 18 cases (4 of the 22 are implementations) and the cpp test file has 18+ tests. One could fix the tests to represent the new layout and sort the test cases to match the requirement, but that is not what configlet complains about.

The "key" sounds like the UUID from the root-folder config.json, but that is set-up correctly as far as I can tell.
Maybe @ErikSchierboom knows a bit better what is going on?

**Comment by BNAndras** [comment]
```
(base) anagy@framework:~/Documents/GitHub/exercism-lfe/exercises/practice/allergies/.meta$ ../../../../bin/configlet sync
Updating cached 'problem-specifications' data...
Checking exercises...
Error: file does not have an `exercises` key:
/home/anagy/Documents/GitHub/exercism-lfe/exercises/practice/allergies/.meta/config.json
```

Configlet is checking the exercise config, not the track config. You need to run that command at the root level repo.

**Comment by tanno1** [comment]
synced toml & updated test file for `phone-numbers`: #867. lmk if you have q's/suggestions, once finalized, i will start on another.

thanks!

**Comment by ErikSchierboom** [comment]
Yep, @BNAndras was right, `configlet` needs to be run from the root directory.

**Comment by tanno1** [comment]
@vaeng, see #870 ^, i submitted another pr for phone numbers after reviewing other pr's from this issue. lmk if there is anything i need to change!

**Comment by BNAndras** [comment]
Whoops, I forgot about protein-translation. I'll take a look at it later this week and tackle high-scores after that.

**Comment by JagritGumber** [comment]
First Time here but could I contribute to prime factors ?

**Comment by vaeng** [comment]
> First Time here but could I contribute to prime factors ? 

Sure thing. Try it out :)

**Comment by JagritGumber** [comment]
I opened a PR but it automatically got closed #895

**Comment by JagritGumber** [comment]
I just saw one of the errors in the merging and clang formatting gives this warning which is treated as an error. Apparently the final test case overflows the bounds of an integer
```
/home/runner/work/cpp/cpp/build_exercises/practice/prime-factors/prime_factors_test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____22()’:
/home/runner/work/cpp/cpp/build_exercises/practice/prime-factors/prime_factors_test.cpp:112:54: error: overflow in conversion from ‘long int’ to ‘int’ changes value from ‘93819012551’ to ‘-670267961’ [-Werror=overflow]
  112 |     const std::vector<int> actual{ prime_factors::of(93819012551) };
      |    
```
Specifically this part

![image](https://github.com/user-attachments/assets/18dcaf3a-6f2a-41b8-a5ac-6e3e23bc09ac)

**Comment by JagritGumber** [comment]
I have got more time tomorrow. May I take Grade School if no one has taken that?

**Comment by siebenschlaefer** [comment]
Sure, that would be great!

**Comment by sz245** [comment]
I could take matching-brackets if no one has?

**Comment by Elahi-cs** [comment]
Hey, I'd like to update the checklist so that we're clearer on which exercises still need an update and which are and aren't taken. @vaeng feel free to just copy and paste it.

```
- [x] allergies (@vaeng) #817  
- [x] anagram (@CadeMichael) #784  
- [x] armstrong-numbers (@ahans) #808  
- [x] bank-account (@KevDi) #826  
- [x] complex-numbers (@KevDi) #829 
- [x] crypto-square (@ahans)  #827 
- [x] gigasecond (@ahans) #810  
- [ ] grade-school (@JagritGumber)
- [x] hamming (@ahans) #775 #789  
- [ ] high-scores  
- [ ] isogram (@BNAndras)  
- [x] luhn (@vaeng) #818  
- [ ] matching-brackets (@sz245 )
- [ ] pangram (@BNAndras)  
- [x] perfect-numbers (@vaeng) #819  
- [x] phone-number  (@tanno1 ) #870 
- [x] prime-factors  (@JagritGumber ) #895 
- [ ] protein-translation  
- [ ] say  
- [x] triangle (@DebbieSan) #787  
- [x] word-count (@vaeng) #820  
```

Also, I will look into updating at least one of the missing ones if I figure out how to work the generator tool.

**Comment by vaeng** [comment]
@BNAndras and @sz245 
Are you still on track to implement the exercises you mentioned, or do you want to put them back into the pool?

**Comment by Elahi-cs** [comment]
I can take whichever one isn't getting worked on, if anyone puts any back into the pool.

**Comment by BNAndras** [comment]
I think the list's out of date for my contributions.
I synced `pangram` in #848 and `isogram` in #849. I went ahead and synced Roman Numerals just now in #914.

**Comment by BNAndras** [comment]
Configlet is warning that `reverse-string` is missing tests which were added a few days after this thread was created.

```
[warn] reverse-string: missing 3 test cases
     - wide characters (1bed0f8a-13b0-4bd3-9d59-3d0593326fa2)
     - grapheme cluster with pre-combined form (93d7e1b8-f60f-4f3c-9559-4056e10d2ead)      
     - grapheme clusters (1028b2c1-6763-4459-8540-2da47ca512d9)
 ```

**Comment by Elahi-cs** [comment]
@BNAndras I submitted #917 to address that.

**Comment by JagritGumber** [comment]
Can I put Grade School back to the pool I am just not getting time.

> I can take whichever one isn't getting worked on, if anyone puts any back into the pool.

**Comment by mAbdulai1234** [comment]
ill take a look at the high scores if that's okay

**Comment by vaeng** [comment]
> ill take a look at the high scores if that's okay

Sure thing, submit your PR when you're done and tag me, so I don't overlook it.

**Comment by cataratoru-fara-cap** [comment]
Hey there! Is the pool up to date? I'd love to help out if there's anything available :D

**Comment by BNAndras** [comment]
> Hey there! Is the pool up to date? I'd love to help out if there's anything available :D

I just checked and these are the unsynced tests in my fork.

```
[warn] bob: missing 1 test case
[warn] grade-school: missing 16 test cases
[warn] matching-brackets: missing 3 test cases
[warn] pig-latin: missing 1 test case
[warn] protein-translation: missing 8 test cases
[warn] reverse-string: missing 3 test cases
```

Bob, Pig Latin, and Reverse String appear to be new. Bob is probably a good starting place.

**Comment by IsaacG** [comment]
I just sent PRs for the ones that made sense. The remaining require maintainer input.

**Comment by marcelweikum** [comment]
Is this still current? Newest sync outputs this:

```
[warn] bob: missing 1 test case
[warn] crypto-square: missing 1 test case
[warn] grade-school: missing 16 test cases
[warn] largest-series-product: missing 2 test cases
[warn] matching-brackets: missing 3 test cases
[warn] pig-latin: missing 1 test case
[warn] protein-translation: missing 8 test cases
[warn] reverse-string: missing 3 test cases
```

I would like to contribute to new / idle tasks if possible! Would be great to update initial list :smile:

**Comment by BNAndras** [comment]
Isaac has open PRs for bob, matching-brackets, pig-latin, and protein-translation.
Elahi-cs has open PRs for grade-school and reverse-string.

That leaves crypto-square and largest-series-product unclaimed.

**Comment by vaeng** [comment]
I will take over Elahi's work and look at Isaac's PR in the next couple of
days

András B Nagy ***@***.***> schrieb am Di., 13. Mai 2025,
07:30:

**Comment by marcelweikum** [comment]
> Isaac has open PRs for bob, matching-brackets, pig-latin, and protein-translation.
> Elahi-cs has open PRs for grade-school and reverse-string.
> 
> That leaves crypto-square and largest-series-product unclaimed.

I would take over both, if it's ok.

**Comment by alienx5499** [comment]
Hi @vaeng @IsaacG @BNAndras 👋

I submitted PR #991 for crypto-square but it was **auto-closed** (normal process for new contributors).

**Current status:** After my changes, `configlet sync` confirms crypto-square is now fully synced (0 missing test cases).

**My approach:** Used official `configlet sync --tests include --update --yes -e crypto-square` to update from "7 chunks" to "8 chunks" test case. All tests pass locally.

**Questions:**
1. If approved, please reopen #991 for review
2. Should I work on `largest-series-product` instead?

Links: #991 (auto-closed)

**Comment by marcelweikum** [comment]
Hey @alienx5499,

there already is a PR for syncing the tests for the exercise crypto square.

The 2 messages above yours discuss this.

The PR you are looking for is #980

**Comment by tonyboboc** [comment]
Hey guys , sorry for asking , how could I help here
