### ISSUE TITLE
Add #48in24 featured exercises

### ISSUE THREAD

**Issue by vaeng** [exercism/cpp#779]
As of Jan 16 2024, the following exercises will show up as featured exercises in #48in24, but are not yet available on the C++ track.

In the order of appearance in the challenge:

- [x] list-ops (Feb-20) (@vaeng, #801)
- [x] linked-list (March-05) (@vaeng, https://github.com/exercism/cpp/pull/567)
- [x] parallel-letter-frequency (March-12) (@ahans, #800)
- [x] zebra-puzzle (May-07) (@rajatnai49, https://github.com/exercism/cpp/pull/788)
- [x] dnd-character (May-21) (@vaeng, #802)
- [x] pig-latin (May-28) (@vaeng, #812)
- [x] yacht (June-11) (@vaeng, #803)
- [x] spiral-matrix (July-09) (@ahans, #807)
- [x] kindergarten-garden (July-30) (@vaeng, #804)
- [x] knapsack (August-27) (@siebenschlaefer, https://github.com/exercism/cpp/pull/795)
- [x] two-bucket (October-08)

Take a look at https://docs.google.com/spreadsheets/d/1X00y60Z6BqYbTMnmmuMYzMoS0eO4KKquSWq2ijXb4Qo/edit#gid=0 to see current status.  
There is now a dedicated matrix with the status of all exercises in #48in24, which tracks have implemented them, and which exercises are featured on a specific track:
https://exercism.org/challenges/48in24/implementation_status

If you want some help to build all the files, you might like the [exercise generation](https://github.com/exercism/cpp/tree/feat--practice-exercise-generator/bin) script I wrote.

**Comment by vaeng** [comment]
I will add list-ops

**Comment by vaeng** [comment]
I already started linked-list a while ago, so please don't start another. I promise to finish it soon 😃

**Comment by rajatnai49** [comment]
Hey, @vaeng I like to start contributing with the zebra-puzzle !

**Comment by vaeng** [comment]
> Hey, @vaeng I like to start contributing with the zebra-puzzle !

Sure thing. Have fun and keep us in the loop. It's not an easy task, so there will be a lot of discussions and feedback.

**Comment by rajatnai49** [comment]
Okay @vaeng I try my best.

**Comment by rajatnai49** [comment]
Hey @vaeng I opened pr but it closed automatically, can you guide me for what steps I have to follow for successfully open the pr

**Comment by siebenschlaefer** [comment]
> I can have a look at `parallel-letter-frequency`.

Good idea! I did look briefly at the [C# version](https://github.com/exercism/csharp/tree/main/exercises/practice/parallel-letter-frequency/) and the [Go version](https://github.com/exercism/go/tree/main/exercises/practice/parallel-letter-frequency). They seem to do similar things, using the mechanisms built into the language (PLINQ / Goroutines).   
But I didn't understand how they actually test that. Good luck, have  fun!

**Comment by siebenschlaefer** [comment]
I would like to contribute 'knapsack'.
See https://github.com/exercism/cpp/pull/795

**Comment by ahans** [comment]
Here goes a (draft) PR for `parallel-letter-frequency`: #800
Need some feedback to finish it up. Details in PR. Thanks!

**Comment by vaeng** [comment]
I will do dnd-character next.

**Comment by vaeng** [comment]
I will do kindergarten-garden in the next days next.

**Comment by ahans** [comment]
I will give spiral-matrix a go!

**Comment by ahans** [comment]
spiral-matrix is ready as #807.

**Comment by vaeng** [comment]
I'll do pig-latin next.

**Comment by ahans** [comment]
@vaeng I actually have it pretty much ready already. PR would come up later tonight. Sorry I didn't mention it here before.

**Comment by ahans** [comment]
@vaeng  Here is the draft PR: #811
If you read this too late and are done with yours already, feel free to just leave it closed.

**Comment by vaeng** [comment]
The last exercise has been merged. Thanks for all the effort, everyone!
